### PR TITLE
Support for Linux and Mac OS X

### PR DESCRIPTION
**Pull request by mslsystems**
Script checks for host operating system and sets the user-data-dir depending on the operating system

### CODE REVIEW

**Comment by BobbyCephy** [comment]
Thank you! I made some additions. Do you agree with them?

**Comment by mslsystems** [comment]
i totally agree with them.

Nice work :)

Dankeschön

**Comment by BobbyCephy** [comment]
Sorry for the mess, it's my first project :satisfied:

**Comment by mslsystems** [comment]
Is it possible to update the pip package with that code?

Greetings and thanks :)

**Comment by BobbyCephy** [comment]
Thanks for the reminder, it has been updated :smiley:

**Pull request merged**
